name: Arquivos compartilhados entre os steps

on:
  workflow_dispatch

jobs:
  entre-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Confere Versao do Ubuntu
        run: cat /etc/os-release

      - name: Gravar uma mensagem
        run: echo "Estou fazendo o curso de Github Actions da LinuxTips" > mensagem.txt

      - name: Ler uma mensagem
        run: cat mensagem.txt